//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public ADMIN()
        {
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public int MAADMIN { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string TENLOAI { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public string AVATAR { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
