//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCNANG_QUYEN
    {
        public CHUCNANG_QUYEN()
        {
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public string MACHUCNANG { get; set; }
        public string TENCN { get; set; }
    
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
