//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        public DONDATHANG()
        {
            this.CTDONDATHANGs = new HashSet<CTDONDATHANG>();
        }
    
        public int MADH { get; set; }
        public int MAKH { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<bool> TINHTRANGDH { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual ICollection<CTDONDATHANG> CTDONDATHANGs { get; set; }
        public virtual KHANHHANG KHANHHANG { get; set; }
    }
}
