//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHANHHANG
    {
        public KHANHHANG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MAKH { get; set; }
        public string HOTENKH { get; set; }
        public string DIENTHOAI { get; set; }
        public string DAICHI { get; set; }
        public string TENDNKH { get; set; }
        public string MATKHAUKH { get; set; }
        public string EMAIL { get; set; }
        public string NGAYSINH { get; set; }
        public string HINHANH { get; set; }
        public string KHOIPHUCMK { get; set; }
    
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    }
}
