//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAUSAC
    {
        public MAUSAC()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MAMAUSAC { get; set; }
        public string TENMAUSAC { get; set; }
        public Nullable<bool> ANHHIEN { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
