//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPKTHUCUNGEntities1 : DbContext
    {
        public QLPKTHUCUNGEntities1()
            : base("name=QLPKTHUCUNGEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CHUCNANG_QUYEN> CHUCNANG_QUYEN { get; set; }
        public DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public DbSet<GIAMGIA> GIAMGIAs { get; set; }
        public DbSet<HINH> HINHs { get; set; }
        public DbSet<KHANHHANG> KHANHHANGs { get; set; }
        public DbSet<KICHTHUOC> KICHTHUOCs { get; set; }
        public DbSet<LOAI> LOAIs { get; set; }
        public DbSet<MAUSAC> MAUSACs { get; set; }
        public DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public DbSet<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
        public DbSet<CTDONDATHANG> CTDONDATHANGs { get; set; }
    }
}
