//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPKHO
    {
        public int MAPHIEUNK { get; set; }
        public System.DateTime NGAYNK { get; set; }
        public int MASP { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
