//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhuKienThuCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.GIAMGIAs = new HashSet<GIAMGIA>();
            this.HINHs = new HashSet<HINH>();
            this.KICHTHUOCs = new HashSet<KICHTHUOC>();
            this.PHIEUNHAPKHOes = new HashSet<PHIEUNHAPKHO>();
            this.CTDONDATHANGs = new HashSet<CTDONDATHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> DONGIAMUA { get; set; }
        public Nullable<decimal> DONGIABAN { get; set; }
        public int MATH { get; set; }
        public int MALOAI { get; set; }
        public Nullable<int> MAMAUSAC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public string THANHTOANON { get; set; }
        public Nullable<bool> ANHHIEN { get; set; }
    
        public virtual ICollection<GIAMGIA> GIAMGIAs { get; set; }
        public virtual ICollection<HINH> HINHs { get; set; }
        public virtual ICollection<KICHTHUOC> KICHTHUOCs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual ICollection<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
        public virtual ICollection<CTDONDATHANG> CTDONDATHANGs { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
